{% set name = "publicsuffixlist" %}
{% set version = "0.10.0.20240411" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/publicsuffixlist-{{ version }}.tar.gz
  sha256: c7a18e4b7b2a1fed628c2828be88fa7245b76a2755797b47b061271ff98bac7a

build:
  entry_points:
    - publicsuffixlist-download = publicsuffixlist.update:updatePSL
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - requests
    # Needed for the CLI

test:
  imports:
    - publicsuffixlist
  commands:
    - pip check
    - publicsuffixlist-download --help
  requires:
    - pip

about:
  home: https://github.com/ko-zu/psl
  summary: publicsuffixlist implement
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
