{% set name = "publicsuffixlist" %}
{% set version = "1.0.2.20260424" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/publicsuffixlist-{{ version }}.tar.gz
  sha256: b1f28102ffc8dc1e83a4d07dec141e1d1822e9b607d14d420519615755f47d55

build:
  entry_points:
    - publicsuffixlist-download = publicsuffixlist.update:updatePSL
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - requests
    # Needed for the CLI

test:
  imports:
    - publicsuffixlist
  commands:
    - pip check
    - publicsuffixlist-download --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ko-zu/psl
  summary: publicsuffixlist implement
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
