{% set name = "publicsuffixlist" %}
{% set version = "0.10.0.20231002" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/publicsuffixlist-{{ version }}.tar.gz
  sha256: a8ef3f5745196fd956bcf6f425b5000450896c616ee6e95130e147e2fae10ccc

build:
  entry_points:
    - publicsuffixlist-download = publicsuffixlist.update:updatePSL
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - requests
    # Needed for the CLI

test:
  imports:
    - publicsuffixlist
  commands:
    - pip check
    - publicsuffixlist-download --help
  requires:
    - pip

about:
  home: https://github.com/ko-zu/psl
  summary: publicsuffixlist implement
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
