{% set name = "publicsuffixlist" %}
{% set version = "1.0.2.20260121" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/publicsuffixlist-{{ version }}.tar.gz
  sha256: dc28d4d26df7d065ab424b017bb77d5bc3d97c0232cd9f343250cd7b08160bbf

build:
  entry_points:
    - publicsuffixlist-download = publicsuffixlist.update:updatePSL
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - requests
    # Needed for the CLI

test:
  imports:
    - publicsuffixlist
  commands:
    - pip check
    - publicsuffixlist-download --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ko-zu/psl
  summary: publicsuffixlist implement
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
